development:
  adapter: postgresql
  database: popsmoke_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: popsmoke_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: popsmoke_production
  pool: 5
  timeout: 5000
